"""Adiciona tabela de Faturamento detalhado

Revision ID: 07e8e7e94267
Revises: 9f06f0300972
Create Date: 2025-12-15 22:39:07.844013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e8e7e94267'
down_revision = '9f06f0300972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_diario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamento_diario', schema=None) as batch_op:
        batch_op.drop_column('faturamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamento_diario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faturamento', sa.FLOAT(), nullable=False))

    op.drop_table('faturamento')
    # ### end Alembic commands ###
