"""add created_at to User

Revision ID: 12330c65dd14
Revises: 653d346f107e
Create Date: 2026-01-31 15:26:31.239518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12330c65dd14'
down_revision = '653d346f107e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
