"""Migração inicial com todas as tabelas

Revision ID: 653d346f107e
Revises: 
Create Date: 2026-01-29 23:07:20.263628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653d346f107e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_carro', sa.String(length=100), nullable=False),
    sa.Column('placa_carro', sa.String(length=20), nullable=True),
    sa.Column('km_atual', sa.Integer(), nullable=False),
    sa.Column('media_consumo', sa.Float(), nullable=False),
    sa.Column('meta_faturamento', sa.Float(), nullable=False),
    sa.Column('periodicidade_meta', sa.String(length=20), nullable=False),
    sa.Column('tipo_meta', sa.String(length=20), nullable=False),
    sa.Column('dias_trabalho_semana', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_combustivel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('abastecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('km_atual', sa.Integer(), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('preco_por_litro', sa.Float(), nullable=False),
    sa.Column('custo_total', sa.Float(), nullable=False),
    sa.Column('tanque_cheio', sa.Boolean(), nullable=True),
    sa.Column('autonomia_restante', sa.Integer(), nullable=True),
    sa.Column('media_consumo_calculada', sa.Float(), nullable=True),
    sa.Column('parametro_id', sa.Integer(), nullable=False),
    sa.Column('tipo_combustivel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parametro_id'], ['parametros.id'], ),
    sa.ForeignKeyConstraint(['tipo_combustivel_id'], ['tipo_combustivel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custo_fixo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('parametro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parametro_id'], ['parametros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamento_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('km_rodado', sa.Integer(), nullable=False),
    sa.Column('parametro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parametro_id'], ['parametros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custo_variavel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria_custo.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_diario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faturamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('lancamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento_diario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faturamento')
    op.drop_table('custo_variavel')
    op.drop_table('lancamento_diario')
    op.drop_table('custo_fixo')
    op.drop_table('abastecimento')
    op.drop_table('user')
    op.drop_table('tipo_combustivel')
    op.drop_table('parametros')
    op.drop_table('categoria_custo')
    # ### end Alembic commands ###
