"""Adiciona campo de media calculada no abastecimento

Revision ID: 9f06f0300972
Revises: 84439e98d096
Create Date: 2025-12-14 22:24:03.389246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f06f0300972'
down_revision = '84439e98d096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abastecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_consumo_calculada', sa.Float(), nullable=True))
        batch_op.alter_column('tanque_cheio',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('custo_variavel', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('parametros', schema=None) as batch_op:
        batch_op.alter_column('placa_carro',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametros', schema=None) as batch_op:
        batch_op.alter_column('placa_carro',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('custo_variavel', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('abastecimento', schema=None) as batch_op:
        batch_op.alter_column('tanque_cheio',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('media_consumo_calculada')

    # ### end Alembic commands ###
